-- MySQL Script generated by MySQL Workbench
-- Tue Jan 24 02:45:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
-- -----------------------------------------------------
-- Schema vehiculo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vehiculo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vehiculo` DEFAULT CHARACTER SET utf8 ;
USE `vehiculo` ;

-- -----------------------------------------------------
-- Table `vehiculo`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehiculo`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(256) NULL,
  `condicion` TINYINT NOT NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vehiculo`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vehiculo`.`vehiculo` (
  `idvehiculo` INT NOT NULL AUTO_INCREMENT,
  `idmarca` INT NULL,
  `patente` VARCHAR(50) NULL,
  `marca` VARCHAR(100) NOT NULL,
  `modelo` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(512) NULL,
  `imagen` VARCHAR(50) NULL,
  `estado` VARCHAR(20) NOT NULL,
  `venta` INT NULL,
  PRIMARY KEY (`idvehiculo`),
  INDEX `fk_vehiculo_marca_idx` (`idmarca` ASC) VISIBLE,
  CONSTRAINT `fk_vehiculo_marca`
    FOREIGN KEY (`idmarca`)
    REFERENCES `vehiculo`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
